version: '3'

services:
  keycloak-db:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # прослушивание порта 5433 на хосте и перенаправление на 5432 в контейнере
    networks:
      - my-network

  app-db:
    image: postgres:13
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    volumes:
      - app-db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # прослушивание порта 5434 на хосте и перенаправление на 5432 в контейнере
    networks:
      - my-network

  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpassword
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    networks:
      - my-network

volumes:
  keycloak-db-data:
  app-db-data:

networks:
  my-network:
